[project]
name = "dlf-backend"
version = "0.1.0"
description = "KI-Suche der Stadt München (Backend)"
readme = "README.md"
authors = [
    { name = "Fabian Reinold", email = "fabian.reinold@muenchen.de" },
    { name = "Michael Jaumann", email = "michael.jaumann@muenchen.de" },
    { name = "Leon Lukas", email = "leon.lukas@muenchen.de" },
    { name = "Sebastian Berger", email = "sebastian.berger@muenchen.de" },
]
maintainers = [
    { name = "Sebastian Berger", email = "sebastian.berger@muenchen.de" },
    { name = "Fabian Reinold", email = "fabian.reinold@muenchen.de" },
]
requires-python = "==3.13.11"
dependencies = [
    "fastapi==0.141.1",
    "gitpython==3.1.60",
    "itsdangerous==2.2.0",
    "langchain-openai==1.6.0",
    "langchain-qdrant==1.1.0",
    "langchain==1.3.18",
    "langfuse==4.15.1",
    "python-dotenv==1.2.3",
    "starlette==1.6.0",
    "qdrant-client[fastembed]==1.19.0",
    "truststore==0.10.4",
    "uvicorn==0.52.4",
    "pyyaml==6.0.3",
    "aiosmtplib==5.1.2",
    "cohere==7.1.0",
]

[dependency-groups]
dev = [
    "ipykernel==7.3.0",
    "pre-commit==4.6.2",
    "pytest==9.1.1",
    "ruff==0.16.5",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
addopts = "-p no:cacheprovider"
